name: Deploy to Git Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone master
        uses: actions/checkout@v2

      - name: init node
        uses: actions/setup-node@v2

      - name: install depedencies
        run: npm install

      - name: deploy
        run: npm run build
